import Head from "next/head";
import { Inter } from "@next/font/google";
import LoginButton from "../components/auth/LoginButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>SwipeCharge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col gap-4 justify-center items-center h-screen w-full">
                <LoginButton />
            </main>
        </>
    );
}
